version: '2.2'

networks:
  yii2-test:

volumes:
  s3_upload_data:

services:

  php-min:
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: 'php'
      target: min
      args:
        - PHP_BASE_IMAGE_VERSION
        - X_LEGACY_GD_LIB
        - PECL_XDEBUG_INSTALL_SUFFIX
        - PECL_MONGODB_INSTALL_SUFFIX
        - PECL_IMAGICK_INSTALL_SUFFIX
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}-min
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
    volumes:
      - ./tests:/tests:delegated
      # Application testing
      - ./app:/app:delegated
      # Composer cache
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    networks:
      yii2-test:
        aliases:
          - php

  php-dev:
    extends:
      service: php-min
    build:
      target: dev
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}

  mysql:
    image: mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/backup:/mnt
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci', '--sql_mode=only_full_group_by' ]
    networks:
      yii2-test:

  minio:
    restart: unless-stopped
    image: minio/minio
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
#      - MINIO_BROWSER_REDIRECT_URL
#      - MINIO_DOMAIN
    #    volumes:
#      - minio_data:/data
#    volumes:
#      - ./data/db:/var/lib/mysql
#      - ./data/backup:/mnt
#    ports:
#      - '${MINIO_PORT:-9000}:9000'
#      - '9020:9020'
    volumes:
      - s3_upload_data:/data/upload
    ports:
      - '9000:9000'
      - '9090:9090'
    command: server /data/upload --console-address ":9090"
    networks:
      yii2-test:

