version: '2.2'
services:

  nginx:
    extends:
      file: docker-compose.yml
      service: php
    build:
      target: nginx-dev
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}-nginx
    ports:
      - '8202:80'

